version: "3.3"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "5000:5000"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "8098:80"
